SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 32768
SecResponseBodyAccess Off
SecAuditEngine On
SecAuditLog /evidence/modsecurity-audit.log
SecAuditLogParts ABIJDEFHZ
Include /etc/modsecurity/crs/crs-setup.conf
Include /usr/share/modsecurity-crs/rules/*.conf
